/**
 * The deployed addresses.
 *
 * Regenerated by `pnpm deploy:testnet`, which writes the broadcast output into this file so
 * the SDK, the CLI, the app and the indexer all read one source.
 */

import type { Deployment } from "./client.js";
import deployments from "./deployments.json" with { type: "json" };

export const knownDeployments = deployments as Record<string, Deployment>;

/** The deployment for a chain id, or the testnet one by default. */
export function deploymentFor(chainId: number | string = 10143): Deployment {
  const d = knownDeployments[String(chainId)];
  if (!d) throw new Error(`no BACKSTOP deployment recorded for chain ${chainId}`);
  return d;
}

export const deployment: Deployment = deploymentFor(10143);
