/**
 * Extract the ABIs the SDK and the app need from the Foundry build output.
 *
 * Run after `forge build`. The generated module is committed so consumers of the SDK do not
 * need a Solidity toolchain.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const CONTRACTS = [
  "AttestationRegistry",
  "AuditRegistry",
  "CoveragePool",
  "PolicyRegistry",
  "Settlement",
  "TicketRegistry",
];

const out = ["// Generated by scripts/gen-abi.mjs. Do not edit.", ""];
for (const name of CONTRACTS) {
  const path = join("contracts", "out", `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(readFileSync(path, "utf8"));
  out.push(`export const ${name.charAt(0).toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(artifact.abi)} as const;`);
  out.push("");
}
// The mock settlement asset, so the demo and the app can mint and approve.
const erc20 = JSON.parse(readFileSync(join("contracts", "out", "MockERC20.sol", "MockERC20.json"), "utf8"));
out.push(`export const erc20Abi = ${JSON.stringify(erc20.abi)} as const;`);
out.push("");

mkdirSync("packages/sdk/src", { recursive: true });
writeFileSync("packages/sdk/src/abi.ts", out.join("\n"));
console.log(`wrote packages/sdk/src/abi.ts with ${CONTRACTS.length + 1} ABIs`);
